### ISSUE TITLE
Does not support multiple cursors

### ISSUE THREAD

**Issue by telmomarques** [markhillard/brackets-caseconverter#1]
Steps to reproduce:
1. Make a multiple cursor selection, across multiple lines (it has to be multiple cursor!)
2. Right click the selection -> "To Lower Case" / "To Upper Case"

Verified behavior:
Every selection is replaced with the text from the first line selected.

Expected behavior:
Selected text should be replaced with upper/lower case equivalent.

Thank you.

**Comment by markhillard** [comment]
@telmomarques, thanks for reporting this. I'm currently looking into [CodeMirror's selection methods](https://codemirror.net/doc/manual.html#api_selection). I'll try a few things out and hopefully fix this soon.

**Comment by markhillard** [comment]
@telmomarques, I've updated the package in the [Brackets Extension Registry](https://registry.brackets.io/), so the next time you open the extension manager you should get an update notice.

**Comment by telmomarques** [comment]
It's working as expected now, thank you!
